# Generated by Django 3.1.7 on 2021-03-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_auto_20210304_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='storage_name',
        ),
    ]
