# Generated by Django 3.1.7 on 2021-03-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0007_auto_20210307_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationclient',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AlterField(
            model_name='operationcontractor',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
    ]
