# Generated by Django 3.1.7 on 2021-03-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0015_auto_20210308_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='atm_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='commentary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
