# Generated by Django 3.1.7 on 2021-03-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0016_auto_20210308_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='atm_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='commentary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='date_in',
            field=models.DateField(null=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='atm',
            name='date_out',
            field=models.DateField(null=True, verbose_name='Дата отгрузки'),
        ),
    ]
