# Generated by Django 3.1.7 on 2021-03-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0017_auto_20210309_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Отгружен', 'Отгружен'), ('В резерве', 'В резерве')], default='В резерве', max_length=10),
        ),
    ]
