# Generated by Django 3.1.7 on 2021-03-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0021_auto_20210310_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontractor',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.customer'),
        ),
    ]
