# Generated by Django 3.1.7 on 2021-03-15 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0022_ordercontractor_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='atm',
        ),
        migrations.AddField(
            model_name='atm',
            name='orders',
            field=models.ManyToManyField(blank=True, to='wms.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_car',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='operation_contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.operationcontractor'),
        ),
        migrations.AddField(
            model_name='order',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.storage'),
        ),
        migrations.AddField(
            model_name='order',
            name='storage_order',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OrderContractor',
        ),
    ]
