# Generated by Django 3.1.7 on 2021-03-15 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistic_order', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('В работе', 'В работе'), ('Закрыта', 'Закрыта'), ('Отменена', 'Отменена'), ('Черновик', 'Черновик')], default='Черновик', max_length=10)),
                ('date_in', models.DateField(blank=True, null=True, verbose_name='Дата приема')),
                ('date_out', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('driver', models.CharField(blank=True, max_length=200, null=True)),
                ('driver_car', models.CharField(blank=True, max_length=200, null=True)),
                ('storage_order', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordercontractor',
            name='atm',
        ),
        migrations.RemoveField(
            model_name='ordercontractor',
            name='client',
        ),
        migrations.RemoveField(
            model_name='ordercontractor',
            name='operation_contractor',
        ),
        migrations.RemoveField(
            model_name='ordercontractor',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='ordercontractor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='operation_contractor',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='contractor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='operationclient',
            old_name='oper_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='operationcontractor',
            old_name='oper_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='operationclient',
            name='oper_cost',
        ),
        migrations.RemoveField(
            model_name='operationcontractor',
            name='oper_cost',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='storage_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='post',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='operationclient',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AddField(
            model_name='operationcontractor',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='rate_in',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='rate_out',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='rate_oversize_in',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='rate_oversize_out',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='rate_oversize_pallet',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='rate_pallet',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='rate_volume',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='atm_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='commentary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='date_in',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='atm',
            name='date_out',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='atm',
            name='size',
            field=models.CharField(choices=[('EUR', 'Габарит EUR'), ('FIN', 'НЕГабарит FIN')], default='EUR', max_length=10),
        ),
        migrations.AlterField(
            model_name='atm',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Отгружен', 'Отгружен'), ('В резерве', 'В резерве')], default='В резерве', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='OrderClient',
        ),
        migrations.DeleteModel(
            name='OrderContractor',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.client'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='operation_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.operationclient'),
        ),
        migrations.AddField(
            model_name='order',
            name='operation_contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.operationcontractor'),
        ),
        migrations.AddField(
            model_name='order',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.storage'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atm',
            name='orders',
            field=models.ManyToManyField(blank=True, to='wms.Order'),
        ),
    ]
