# Generated by Django 3.1.7 on 2021-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_auto_20210315_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='operation',
        ),
        migrations.AddField(
            model_name='order',
            name='operation',
            field=models.ManyToManyField(blank=True, to='wms.Operation'),
        ),
    ]
