# Generated by Django 3.1.7 on 2021-03-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_remove_storage_storage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='contractor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='operationclient',
            old_name='oper_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='operationclient',
            old_name='oper_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='operationcontractor',
            old_name='oper_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='operationcontractor',
            old_name='oper_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rate_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='name',
        ),
    ]
