# Generated by Django 3.1.7 on 2021-03-16 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_auto_20210316_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='atm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.atm'),
        ),
        migrations.AddField(
            model_name='order',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
