# Generated by Django 3.1.7 on 2021-03-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_auto_20210307_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='rate_in',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='rate_out',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='rate_pallet',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='rate_volume',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
    ]
