# Generated by Django 3.1.7 on 2021-03-29 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_auto_20210316_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='atm',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.atm')),
                ('order', models.ManyToManyField(to='wms.Order')),
            ],
        ),
    ]
