# Generated by Django 3.1.7 on 2021-03-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0008_auto_20210307_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='rate_oversize',
            field=models.DecimalField(decimal_places=2, max_digits=9999, null=True),
        ),
    ]
