# Generated by Django 3.1.7 on 2021-05-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0009_auto_20210429_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='date_in',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='atm',
            name='date_out',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки'),
        ),
    ]
