# Generated by Django 3.1.7 on 2021-05-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0010_auto_20210505_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='photo_4',
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('atm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.atm')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.order')),
            ],
        ),
    ]
