# Generated by Django 3.1.7 on 2021-05-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0011_auto_20210505_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm',
            name='date_in',
        ),
        migrations.RemoveField(
            model_name='atm',
            name='date_out',
        ),
    ]
