# Generated by Django 3.1.7 on 2021-03-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0013_auto_20210308_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='status',
            field=models.CharField(choices=[('in_store', 'Принят'), ('out', 'Отгружен'), ('in_reserve', 'В резерве')], default='in_reserve', max_length=10),
        ),
    ]
