# Generated by Django 3.2.2 on 2021-05-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0013_auto_20210507_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPhoto',
            new_name='AtmPhoto',
        ),
    ]
