# Generated by Django 3.1.7 on 2021-03-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0014_auto_20210308_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='date_in',
            field=models.DateTimeField(null=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='atm',
            name='date_out',
            field=models.DateTimeField(null=True, verbose_name='Дата отгрузки'),
        ),
    ]
