# Generated by Django 3.2.2 on 2021-05-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0015_rename_photo_atmphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmphoto',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
