# Generated by Django 3.1.7 on 2021-03-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0018_auto_20210309_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='date_in',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='atm',
            name='date_out',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки'),
        ),
    ]
