# Generated by Django 3.1.7 on 2021-03-09 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0019_auto_20210309_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderclient',
            name='storage',
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='atm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.atm'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.client'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.customer'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='date_in',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='date_out',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='operation_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.operationclient'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Закрыта', 'Закрыта'), ('Отменена', 'Отменена'), ('Черновик', 'Черновик')], default='Черновик', max_length=10),
        ),
    ]
